## Numpy array and basics
learn about numpy with chai aur code

In [4]:
import numpy as np

In [5]:
## Creating arrays from list


In [6]:
arr_1d= np.array([1,2,3,4,5])
print("1D array:",arr_1d)


arr_2d= np.array([[1,2,3,],[4,5,6]])
print("2D array:",arr_2d)


1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


In [7]:
## List vs numpy arrays

In [15]:
py_list=[1,2,3]
print("python list multiplication", py_list * 2)


np_array=np.array([1,2,3])
print("pyhton array multiplication", np_array * 2)


import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List operation time:",time.time()-start)


start=time.time()
np_array=np.arange(1000000)*2
print("\n Numpy operation time:",time.time()-start)


python list multiplication [1, 2, 3, 1, 2, 3]
pyhton array multiplication [2 4 6]

 List operation time: 0.17711544036865234

 Numpy operation time: 0.008701801300048828


In [16]:
### Creating Arrays from Scratch

In [20]:
zeros=np.zeros((3,4))
print("zeros arrays:\n", zeros)

ones=np.ones((2,3))
print("one array:\n", ones)

full=np.full((2,3),7)
print("full array:\n", full)



random=np.random.random((2,3))
print("random array:\n", random)



zeros arrays:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[7 7 7]
 [7 7 7]]
random array:
 [[0.95356394 0.97684049 0.05288022]
 [0.45407932 0.95485724 0.76798852]]
