## Numpy Arrays operations

In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing:",arr[2:7])
print("with slicing",arr[1:8:2])
print("Negative indexing",arr[-3])

Basic Slicing: [3 4 5 6 7]
with slicing [2 4 6 8]
Negative indexing 8


In [ ]:
arr_2d=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("Specific element",arr_2d[1,2])
print("Entire row",arr_2d[1])
print("Entire row",arr_2d[:,2]) 


Specific element 6
Entire row [4 5 6]
Entire row [3 6 9]


## Sorting

In [12]:
unsorted=np.array([1,8,3,1,5,5,7,9,8])
print("Sorted Array",np.sort(unsorted))


arr_2d_unsorted=np.array([[3,1],
                      [1,2],
                      [2,3]])
print("Sorted 2D array by column",np.sort(arr_2d_unsorted,axis=1))


Sorted Array [1 1 3 5 5 7 8 8 9]
Sorted 2D array by column [[1 3]
 [1 2]
 [2 3]]


## Filtering


In [17]:
numbers=np.array([1,2,3,4,5,6,7,8,9])
even_number=numbers[numbers % 2 ==0]
print("Even Numbers:",even_number)

Even Numbers: [2 4 6 8]


## Filter with Mask

In [18]:
mask=numbers>5
print("Numbers greater than 5:",numbers[mask])

Numbers greater than 5: [6 7 8 9]


## Fancy Indexing vs np.where() 

In [39]:
indices=[0,2,4]
print(numbers[indices])


where_result=np.where(numbers>5)
print(where_result)
print("NP where",numbers[where_result])



condition_array=np.where(numbers > 5,"true" ,"false")
print(condition_array)


[1 3 5]
(array([5, 6, 7, 8]),)
NP where [6 7 8 9]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true']


## Adding or removing data

In [40]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

combined=np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]
